[supabase]
url = "https://lviiizpsnytdhegfffmw.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aWlpenBzbnl0ZGhlZ2ZmZm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDE0MzEsImV4cCI6MjA3MjUxNzQzMX0.rey73xsia2obOUteW6zoUcnQvxfA3tq7au2QxxIv0Ic"

[app]
bot_username = "HealthWhispererBot"
telegram_token = "8244400680:AAF2yQKACALdP5DL8coeAd-biycrhH32bxs"
gemini_api_key = "AIzaSyBummsAof-b2_nc7iRteLXJMUWxHgGAduE"